"""    mode, dif, bor = menu("SNAKE",
                          "Lancer la partie",
                          ["Mode", "Classique", "Dingue"],
                          ["Difficulté", "Moyen", "Difficile", " Extrême",
                            "Facile"],
                          ["Bordures", "Mortelles", "Téléportation"],
                          ["Commandes", " Nav: Flèches", "Menu: HOME",
                            "Rejouer: OK"],
                          ["Crédits","Arthur J.","Vincent R."])"""
                          mode, ope, dif, rep = menu("Automatismes en calcul mental",
                                "Calculer [OK]",
                                ["Mode", "Classique", "Rapide"],
                                ["Opération(s)", "+", "-", "x", "/", "+ -",
                                  " x / ", "+ - x", "+ - x /"],
                                ["Difficulté", "  modéré", "difficile",
                                  "expert", "facile"],
                                ["Répétition", 42, 50, 100, 120, 20],
                                ["Crédits", "Site web$nsi.xyz/calcul",
                                  "Auteur$Kevin Fedyna",
                                  "Contributeur$Vincent ROBERT"])
